Add Sequence Diagram for Stats, Allocate, and ViewQuota Commands
AY2425S1-CS2113-W12-2/tp pull request #91
Opened 2024-10-29 08:42 UTC by ThisisXXZ

main changes in include:
* Sequence Diagrams for ``stats``, ``viewQuota`` commands
* Description for ``stats``, ``viewQuota``, and ``allocator`` commands

2024-10-29 08:54 UTC, isaacsaw25 commented on docs/UML_Diagrams/ViewQuotaSequence.drawio.svg
Do close the gap in the activation bar for the `:viewQuoteCommand` 😅

2024-10-29 08:54 UTC, isaacsaw25 commented on docs/UML_Diagrams/StatSequence.drawio.svg
Do close the gap in the activation bar for the `:StatCommand` 😅

2024-10-29 08:55 UTC, isaacsaw25 requested changes
As per comments, minor changes to be made 😈 😮

2024-10-29 09:40 UTC, paulktham commented on docs/UML_Diagrams/ViewQuotaSequence.drawio.svg
In between spotsLeft:int returning and calling getFullName() there should be a gap in the university activation block

2024-10-30 03:34 UTC, isaacsaw25 approved these changes
Looks good for now 👌 Might have to look into resolving the transparent background, as it may cause compatibility issues 😓

2024-10-30 03:34 UTC, merged

2024-10-30 03:34 UTC, paulktham approved these changes
nice changes!

2024-10-30 03:46 UTC, ThisisXXZ commented
> Looks good for now 👌 Might have to look into resolving the transparent background, as it may cause compatibility issues 😓

The background is correctly displayed in both the markdown preview and the DG website, so I guess it is OK by now?